### ISSUE TITLE
assets/burgr-logo.svg missing

### ISSUE THREAD

**Issue by LeoErcolanelli** [algolia/polyconf16#2]
@gianluca Missing file :(

**Comment by proudlygeek** [comment]
It's versioned, look here: 
https://github.com/algolia/polyconf16/blob/master/front/src/assets/burgr-logo.svg

**Comment by LeoErcolanelli** [comment]
You are right, maybe we lack a dependency for the import not to fail?

**Comment by proudlygeek** [comment]
Good catch, Webpack didn't complain and I forgot to add `--save` on the package. Fixed in a8a2dc8

![star-trek-frustrated-facepalm-6OWIl75ibpuFO](https://media1.giphy.com/media/6OWIl75ibpuFO/giphy.gif)
